// src/lib/components/Sorter.svelte
<script lang="ts">
	import Caret from "./Caret.svelte";

	export let selected: "naw" | "up" | "down" | undefined = undefined;

	import { createEventDispatcher } from "svelte";

	const dispatch = createEventDispatcher();

	function onClick() {
		dispatch("message");
	}
</script>

<button class="flex items-center group mr-4" on:click={onClick}>
	<span class="font-bold mr-1"><slot /></span>
	<div
		class={`relative top-[1px] transition-all sm:group-hover:rotate-45 ${
			selected === "naw" ? "opacity-0 group-hover:opacity-25 group-hover:rotate-0" : ""
		}`}
	>
		<div class={`${selected === "up" ? "rotate-180" : "rotate-0"} transition-transform`}>
			<Caret />
		</div>
	</div>
</button>

// components/Sorter.tsx
import { ReactNode } from "react";
import CaretDown from "./CaretDown";

export default function Sorter({
	children,
	selected,
	onClick,
}: {
	children: ReactNode;
	selected?: "naw" | "up" | "down";
	onClick: () => void;
}) {
	return (
		<button className="flex items-center group mx-4" onClick={onClick}>
			<span className="font-bold mr-1">{children}</span>
			<div
				className={`relative top-[1px] transition-all group-hover:rotate-12 ${
					selected === "naw"
						? "opacity-0 group-hover:opacity-25 group-hover:rotate-0"
						: ""
				}`}
			>
				<div
					className={`${
						selected === "up" ? "rotate-180" : "rotate-0"
					} transition-transform`}
				>
					<CaretDown />
				</div>
			</div>
		</button>
	);
}
