// src/routes/faq.svelte
<div class="w-screen min-h-screen  bg-green-300 flex justify-center pt-20 ">
    <article class="prose">
        <h1>Frequently Asked Questions</h1>
        <h2>How are people ranked?</h2>
        <p>This way</p>
        <h2>Who is included?</h2>
        <p>{"The Forbes World's Billionaires List"}</p>
        <h2>Who made this?</h2>
        <p>Conor</p>
        <h2>I disagree with how you ranked my favorite billionaire. Where can I tell you?</h2>
        <p>Here</p>
    </article>
</div>

// pages/faq.tsx
// function QA() {
//     return <>
//     <h1 className="text-xl"></h1>
//     <p></p>
//     </>
// }

export default function Faq() {
	return (
		<div className="w-screen min-h-screen  bg-green-300 flex justify-center pt-20 ">
			<article className="prose">
				<h1>Frequently Asked Questions</h1>
				<h2>How are people ranked?</h2>
				<p>This way</p>
				<h2>Who is included?</h2>
				<p>{"The Forbes World's Billionaires List"}</p>
				<h2>Who made this?</h2>
				<p>Conor</p>
				<h2>I disagree with how you ranked my favorite billionaire. Where can I tell you?</h2>
				<p>Here</p>
			</article>
		</div>
	);
}
